# Generated by Django 3.0.2 on 2020-01-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer_detail',
            name='preferred_lang',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
